# Measuring the central tendency

In [1]:
import pandas as pd

In [6]:
a= pd.read_csv("mode.csv")
a

     Student  Overall Marks  Gender    Subject
0      Anish             97    Male    English
1    Rishabh             83    Male    English
2       Ajay             78    Male    Physics
3    Abhinav             86    Male  Chemistry
4     Anurag             91    Male    English
5      Ajeet             15    Male    Physics
6      Varun             83    Male  Chemistry
7     Rajeev             64    Male  Chemistry
8     sanjay             66    Male  Chemistry
9      NISHA             58  Female    Physics
10    SURESH             62    Male    Physics
11    Aniket             62    Male    English
12      manu             20    Male    Physics
13      ALOK             85    Male    English
14    Pranav             49    Male  Chemistry
15      Deep             92    Male    English
16  Prashant             21    Male    Physics
17     Kunal             15    Male    Physics
18     Soham             46    Male  Chemistry
19     mayur            100    Male  Chemistry
20     shaan             18    Male  Chemistry
21  shivangi             70  Female    Physics
22       Sam             82  Female    English
23     Dhruv             88    Male    English
24    tushar             88    Male    English
25    Neelam            100  Female  Chemistry
26      yash             86    Male    Physics
27     Nitin             60    Male    English
28      Arun             88    Male  Chemistry
29     Sumit             19    Male    Physics
..       ...            ...     ...        ...
70  Abhishek             91    Male  Chemistry
71    simran              0  Female    Physics
72     Angel             99  Female    English
73    juvina             78  Female    English
74     ajith             63    Male    English
75     Tanya             98  Female  Chemistry
76   Vaibhav             98    Male    Physics
77     Sneha             98  Female    English
78    prince             64    Male  Chemistry
79       jay             81    Male    Physics
80   Avinash             76    Male    English
81   sanchit             80    Male  Chemistry
82     Rohan             97    Male    Physics
83    dinesh             18    Male    Physics
84      Lily             90  Female  Chemistry
85    diksha             71  Female  Chemistry
86    vishal             67    Male    English
87    Rutuja             73  Female  Chemistry
88     akash             93    Male    Physics
89    mahesh             78    Male    Physics
90    vedant             74    Male    English
91       Ram             99    Male    Physics
92      Dawn             73  Female    Physics
93     ankur             17    Male  Chemistry
94    Smriti              0  Female  Chemistry
95   Aaditya             77    Male  Chemistry
96     vivek             55    Male    Physics
97     Tisha              7  Female    English
98    Raghav             73    Male    English
99    Ishita             82  Female  Chemistry

[100 rows x 4 columns]

In [8]:
a['Gender'].mode()

0    Male
dtype: object